// Auto-generated specialized encode functions for common configurations.
// The actual implementations are generated by build.rs into OUT_DIR/codegen_encode.rs.

#[cfg(all(
    feature = "simd-avx2",
    target_arch = "x86_64",
    not(target_env = "msvc"),
    not(any(target_os = "android", target_os = "ios"))
))]
include!(concat!(env!("OUT_DIR"), "/codegen_encode.rs"));

#[cfg(not(all(
    feature = "simd-avx2",
    target_arch = "x86_64",
    not(target_env = "msvc"),
    not(any(target_os = "android", target_os = "ios"))
)))]
pub(crate) fn try_encode_codegen_avx2(
    _data_shard_count: usize,
    _parity_shard_count: usize,
    _parity_rows: &[&[u8]],
    _data: &[&[u8]],
    _parity: &mut [&mut [u8]],
    _shard_len: usize,
) -> bool {
    false
}
