// Auto-generated specialized encode functions for common configurations.
// The actual implementations are generated by build.rs into OUT_DIR/codegen_encode.rs.

#[cfg(all(
    feature = "simd-avx2",
    target_arch = "x86_64",
    not(target_env = "msvc"),
    not(any(target_os = "android", target_os = "ios"))
))]
include!(concat!(env!("OUT_DIR"), "/codegen_encode.rs"));

#[cfg(not(all(
    feature = "simd-avx2",
    target_arch = "x86_64",
    not(target_env = "msvc"),
    not(any(target_os = "android", target_os = "ios"))
)))]
pub(crate) fn try_encode_codegen_avx2(
    _data_shard_count: usize,
    _parity_shard_count: usize,
    _parity_rows: &[&[u8]],
    _data: &[&[u8]],
    _parity: &mut [&mut [u8]],
    _shard_len: usize,
) -> bool {
    false
}

#[inline]
fn avx2_codegen_available() -> bool {
    #[cfg(all(feature = "std", target_arch = "x86_64"))]
    {
        return avx2_codegen_available_for(std::is_x86_feature_detected!("avx2"));
    }

    #[cfg(all(feature = "std", not(target_arch = "x86_64")))]
    {
        false
    }

    #[cfg(not(feature = "std"))]
    avx2_codegen_available_for(cfg!(all(target_arch = "x86_64", target_feature = "avx2")))
}

#[inline]
fn avx2_codegen_available_for(avx2_available: bool) -> bool {
    avx2_available
}

#[cfg(all(
    test,
    feature = "simd-avx2",
    target_arch = "x86_64",
    not(target_env = "msvc"),
    not(any(target_os = "android", target_os = "ios"))
))]
mod tests {
    use super::*;

    #[test]
    fn no_runtime_avx2_returns_fallback_without_writing_parity() {
        let mut parity = [0xa5; 1];
        let mut parity_refs = [&mut parity[..]];

        assert!(!try_encode_codegen_avx2_with_avx2_available(
            false,
            4,
            2,
            &[],
            &[],
            &mut parity_refs,
            1,
        ));
        assert_eq!(parity, [0xa5; 1]);
    }
}
